name: Deploy
on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    name: Publish webextension
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build
        run: |
          yarn
          yarn craco build
          zip -r dist.zip build
      - name: Upload & release
        uses: mnao305/chrome-extension-upload@v4.0.1
        with:
          file-path: dist.zip
          extension-id: ${{secrets.CHROME_APP_ID}}
          client-id: ${{ secrets.CHROME_APP_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_APP_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_APP_REFRESH_TOKEN }}
          publish: false
